### ISSUE TITLE
红色字体太显眼

### ISSUE THREAD

**Issue by jaybowang** [igiu1988/XcodeMediaLibraryTweak#1]
默认字体颜色能保持一致么？要高亮的话建议设置成可选项。
红色看起来太不舒服了~

好插件 👍

**Comment by igiu1988** [comment]
可以，果然还是有需求才有动力呀~这几天内我改一个可以自己选择颜色的版本出来~谢谢你的意见 ^_^ 😄

**Comment by igiu1988** [comment]
前些日子已改好~
