### ISSUE TITLE
this may cause some ui problem in Xcode 7.0

### ISSUE THREAD

**Issue by oit63** [igiu1988/XcodeMediaLibraryTweak#2]
I installed this, find that my Xcode UI like ToolBar can't be save, and be no icons. additionally, the inspector in .xib, after select each control , the attribute tab will show no selection, same as some other inspector tab.

**Comment by igiu1988** [comment]
Can you write in Chinese，I saw your profile, I think you are a Chinese。我看了你的个人资料，觉得你可能是个中国人。咱俩中文交流。

**Comment by oit63** [comment]
我想用一下你的插件，但是发现装好以后打开xib文件，选择控件以后，就显示no selection

**Comment by igiu1988** [comment]
可以截图我看看，没有想明白是什么样子的。我这儿是正常的。另外，你的是Xcode 7.0正式版吧

**Comment by oit63** [comment]
嗯，正式版

**Comment by oit63** [comment]
那我晚上截个图传上来

**Comment by oit63** [comment]
谢谢，我回家在book上装了Tweak之后，可以正常使用。
